In [6]:
import numpy as np
import pandas as pd

In [7]:
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)

# Create a 3D NumPy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(array_3d)

# Create an array filled with zeros
zeros_array = np.zeros((3, 3))
print("\nArray of Zeros:")
print(zeros_array)

# Create an array filled with ones
ones_array = np.ones((2, 4))
print("\nArray of Ones:")
print(ones_array)

# Create an array with a range of values
range_array = np.arange(10)
print("\nRange Array:")
print(range_array)

# Create an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
print("\nLinspace Array:")
print(linspace_array)

# Create a random array
random_array = np.random.rand(3, 3)
print("\nRandom Array:")
print(random_array)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Range Array:
[0 1 2 3 4 5 6 7 8 9]

Linspace Array:
[0.   0.25 0.5  0.75 1.  ]

Random Array:
[[0.90191711 0.27870981 0.54790157]
 [0.35712673 0.91499824 0.56648475]
 [0.85149083 0.81622794 0.69531051]]
